image: node:17

stages:
  # - test
  - pages

test:
  stage: test
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run jest
    # Check this: https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html
  only:
    - master

pages:
  stage: pages
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
